spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_platform?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/boxim}

minio:
  endpoint: http://127.0.0.1:9000 #内网地址
  domain: http://127.0.0.1:9000  #外网访问地址
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: box-im
  imagePath: image
  filePath: file
  videoPath: video
  expireIn: 180 # 文件过期时间,单位:天

webrtc:
  max-channel: 9 # 多人通话最大通道数量，最大不能超过16,建议值:4,9,16
  iceServers:
    - urls: stun:stun.l.google.com:19302

sms:
  platform: aliyun  # 目前仅支持阿里云短信
  access-key: ${SMS_ACCESS_KEY}
  secret-key: ${SMS_SECRET_KEY}
  sign-name: xxx科技 # 短信签名,需在阿里云控制台审核通过
  template-id: SMS_481125065 # 短信模版id,验证码变量必须为: ${code}

mail:
  host: smtp.163.com
  port: 465
  ssl: true
  name: 广州联盒科技
  from: ${MAIL_FROM}
  pass: ${MAIL_PASS}
  subject: '您收到一条注册验证码'
  content: '您正在注册盒子IM账号,验证码为:  ${code} ,有效期为5分钟'

registration:
  mode:
    - username #用户名注册
    - phone # 手机注册,需开启短信功能
    - email # 邮箱注册,需开启短信功能
